export const SENSITIVITY = Object.freeze({
  organization: "LOW",
  department: "LOW",
  position: "LOW",
  service: "LOW",
  schedule: "LOW",
  notification: "LOW",
  appointment: "MEDIUM",
  queue: "MEDIUM",
  profile: "HIGH",
  user: "HIGH",
  staff: "HIGH",
  medicalRecord: "CRITICAL",
  consultation: "CRITICAL",
  prescription: "CRITICAL",
  auditLog: "CRITICAL",
});

export const ACTION_ROLES = Object.freeze({
  "appointment:create": ["student", "staff", "admin", "super_admin"],
  "appointment:read": ["student", "staff", "admin", "super_admin"],
  "appointment:update": ["staff", "admin", "super_admin"],
  "appointment:delete": ["admin", "super_admin"],
  "queue:create": ["student"],
  "queue:read": ["student", "staff", "admin", "super_admin"],
  "queue:update": ["staff", "admin", "super_admin"],
  "medicalRecord:create": ["student"],
  "medicalRecord:read": ["student", "staff", "admin", "super_admin"],
  "medicalRecord:update": ["student", "staff", "admin", "super_admin"],
  "medicalRecord:delete": [],
  "consultation:create": ["staff", "admin", "super_admin"],
  "consultation:read": ["staff", "admin", "super_admin"],
  "consultation:update": ["staff", "admin", "super_admin"],
  "consultation:delete": ["staff", "admin", "super_admin"],
  "prescription:create": ["staff", "admin", "super_admin"],
  "prescription:read": ["staff", "admin", "super_admin"],
  "prescription:update": ["staff", "admin", "super_admin"],
  "prescription:delete": ["admin", "super_admin"],
  "auditLog:read": ["admin", "super_admin"],
  "auditLog:delete": ["super_admin"],
});